onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_spi/spi_top/sys_clk_i
add wave -noupdate /tb_top_spi/spi_top/periph_clk_i
add wave -noupdate /tb_top_spi/spi_top/rstn_i
add wave -noupdate /tb_top_spi/spi_top/dft_test_mode_i
add wave -noupdate /tb_top_spi/spi_top/dft_cg_enable_i
add wave -noupdate /tb_top_spi/spi_top/spi_eot_o
add wave -noupdate /tb_top_spi/spi_top/spi_event_i
add wave -noupdate /tb_top_spi/spi_top/cfg_data_i
add wave -noupdate /tb_top_spi/spi_top/cfg_addr_i
add wave -noupdate /tb_top_spi/spi_top/cfg_valid_i
add wave -noupdate /tb_top_spi/spi_top/cfg_rwn_i
add wave -noupdate /tb_top_spi/spi_top/cfg_data_o
add wave -noupdate /tb_top_spi/spi_top/cfg_ready_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_startaddr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_size_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_continuous_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_en_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_clr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_en_i
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_pending_i
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_curr_addr_i
add wave -noupdate /tb_top_spi/spi_top/cfg_cmd_bytes_left_i
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_startaddr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_size_o
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_continuous_o
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_en_o
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_clr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_en_i
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_pending_i
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_curr_addr_i
add wave -noupdate /tb_top_spi/spi_top/cfg_rx_bytes_left_i
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_startaddr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_size_o
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_continuous_o
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_en_o
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_clr_o
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_en_i
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_pending_i
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_curr_addr_i
add wave -noupdate /tb_top_spi/spi_top/cfg_tx_bytes_left_i
add wave -noupdate /tb_top_spi/spi_top/cmd_req_o
add wave -noupdate /tb_top_spi/spi_top/cmd_gnt_i
add wave -noupdate /tb_top_spi/spi_top/cmd_datasize_o
add wave -noupdate /tb_top_spi/spi_top/cmd_i
add wave -noupdate /tb_top_spi/spi_top/cmd_valid_i
add wave -noupdate /tb_top_spi/spi_top/cmd_ready_o
add wave -noupdate /tb_top_spi/spi_top/data_tx_req_o
add wave -noupdate /tb_top_spi/spi_top/data_tx_gnt_i
add wave -noupdate /tb_top_spi/spi_top/data_tx_datasize_o
add wave -noupdate /tb_top_spi/spi_top/data_tx_i
add wave -noupdate /tb_top_spi/spi_top/data_tx_valid_i
add wave -noupdate /tb_top_spi/spi_top/data_tx_ready_o
add wave -noupdate /tb_top_spi/spi_top/data_rx_datasize_o
add wave -noupdate /tb_top_spi/spi_top/data_rx_o
add wave -noupdate /tb_top_spi/spi_top/data_rx_valid_o
add wave -noupdate /tb_top_spi/spi_top/data_rx_ready_i
add wave -noupdate /tb_top_spi/spi_top/spi_clk_o
add wave -noupdate /tb_top_spi/spi_top/spi_csn0_o
add wave -noupdate /tb_top_spi/spi_top/spi_csn1_o
add wave -noupdate /tb_top_spi/spi_top/spi_csn2_o
add wave -noupdate /tb_top_spi/spi_top/spi_csn3_o
add wave -noupdate /tb_top_spi/spi_top/spi_oen0_o
add wave -noupdate /tb_top_spi/spi_top/spi_oen1_o
add wave -noupdate /tb_top_spi/spi_top/spi_oen2_o
add wave -noupdate /tb_top_spi/spi_top/spi_oen3_o
add wave -noupdate /tb_top_spi/spi_top/spi_sdo0_o
add wave -noupdate /tb_top_spi/spi_top/spi_sdo1_o
add wave -noupdate /tb_top_spi/spi_top/spi_sdo2_o
add wave -noupdate /tb_top_spi/spi_top/spi_sdo3_o
add wave -noupdate /tb_top_spi/spi_top/spi_sdi0_i
add wave -noupdate /tb_top_spi/spi_top/spi_sdi1_i
add wave -noupdate /tb_top_spi/spi_top/spi_sdi2_i
add wave -noupdate /tb_top_spi/spi_top/spi_sdi3_i
add wave -noupdate /tb_top_spi/spi_top/s_status
add wave -noupdate /tb_top_spi/spi_top/s_tx_start
add wave -noupdate /tb_top_spi/spi_top/s_tx_size
add wave -noupdate /tb_top_spi/spi_top/s_tx_qpi
add wave -noupdate /tb_top_spi/spi_top/s_tx_done
add wave -noupdate /tb_top_spi/spi_top/s_tx_data
add wave -noupdate /tb_top_spi/spi_top/s_tx_data_valid
add wave -noupdate /tb_top_spi/spi_top/s_tx_data_ready
add wave -noupdate /tb_top_spi/spi_top/s_rx_start
add wave -noupdate /tb_top_spi/spi_top/s_rx_size
add wave -noupdate /tb_top_spi/spi_top/s_rx_qpi
add wave -noupdate /tb_top_spi/spi_top/s_rx_done
add wave -noupdate /tb_top_spi/spi_top/s_rx_data
add wave -noupdate /tb_top_spi/spi_top/s_rx_data_valid
add wave -noupdate /tb_top_spi/spi_top/s_rx_data_ready
add wave -noupdate /tb_top_spi/spi_top/s_udma_rx_data
add wave -noupdate /tb_top_spi/spi_top/s_udma_rx_data_valid
add wave -noupdate /tb_top_spi/spi_top/s_udma_rx_data_ready
add wave -noupdate /tb_top_spi/spi_top/s_udma_tx_data
add wave -noupdate /tb_top_spi/spi_top/s_udma_tx_data_valid
add wave -noupdate /tb_top_spi/spi_top/s_udma_tx_data_ready
add wave -noupdate /tb_top_spi/spi_top/s_spi_data_tx
add wave -noupdate /tb_top_spi/spi_top/s_spi_data_tx_valid
add wave -noupdate /tb_top_spi/spi_top/s_spi_data_tx_ready
add wave -noupdate /tb_top_spi/spi_top/s_udma_cmd
add wave -noupdate /tb_top_spi/spi_top/s_udma_cmd_valid
add wave -noupdate /tb_top_spi/spi_top/s_udma_cmd_ready
add wave -noupdate /tb_top_spi/spi_top/s_spi_cmd
add wave -noupdate /tb_top_spi/spi_top/s_spi_cmd_valid
add wave -noupdate /tb_top_spi/spi_top/s_spi_cmd_ready
add wave -noupdate /tb_top_spi/spi_top/s_clkdiv_data
add wave -noupdate /tb_top_spi/spi_top/s_clkdiv_valid
add wave -noupdate /tb_top_spi/spi_top/s_clkdiv_ack
add wave -noupdate /tb_top_spi/spi_top/s_clkdiv_en
add wave -noupdate /tb_top_spi/spi_top/s_events
add wave -noupdate /tb_top_spi/spi_top/s_clk_spi
add wave -noupdate /tb_top_spi/spi_top/s_spi_eot
add wave -noupdate /tb_top_spi/spi_top/s_cfg_cpol
add wave -noupdate /tb_top_spi/spi_top/s_cfg_cpha
add wave -noupdate /tb_top_spi/spi_top/s_tx_customsize
add wave -noupdate /tb_top_spi/spi_top/s_rx_customsize
add wave -noupdate /tb_top_spi/spi_top/s_tx_bitsword
add wave -noupdate /tb_top_spi/spi_top/s_tx_wordtransf
add wave -noupdate /tb_top_spi/spi_top/s_tx_lsbfirst
add wave -noupdate /tb_top_spi/spi_top/s_rx_bitsword
add wave -noupdate /tb_top_spi/spi_top/s_rx_wordtransf
add wave -noupdate /tb_top_spi/spi_top/s_rx_lsbfirst
add wave -noupdate -divider -height 30 slave_sim
add wave -noupdate /tb_top_spi/spi_slave/sclk
add wave -noupdate /tb_top_spi/spi_slave/mosi
add wave -noupdate /tb_top_spi/spi_slave/miso
add wave -noupdate /tb_top_spi/spi_slave/ss
add wave -noupdate /tb_top_spi/spi_slave/sample_ev
add wave -noupdate /tb_top_spi/spi_slave/change_ev
add wave -noupdate /tb_top_spi/spi_slave/miso_r
add wave -noupdate /tb_top_spi/spi_slave/rd_data
add wave -noupdate /tb_top_spi/spi_slave/miso_byte
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
